server:
  port: 8081

spring:

  file:
    upload-dir: '/home/ec2-user/uploads'

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: postgres


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

security:
  jwt:
    secret-key: secret
